global:
  scrape_interval:     10s # By default, scrape targets every 15 seconds.
  evaluation_interval: 10s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # The labels to add to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).

  external_labels:
    monitor: 'master'

# Alerting
alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - localhost:9093

# Rule files specifies a list of files from which rules are read.
rule_files:
  - /etc/prometheus/rules/*.rules

# A list of scrape configurations.
scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 10s
    scrape_timeout:  10s
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance: prometheus

  - job_name: linux
    static_configs:
      - targets: ['localhost:9100']
        labels:
          instance: prometheus