---

- name: run the main role
  become: true
  become_method: sudo
  become_user: root
  hosts: all
  vars:
    prometheus_components:
      - prometheus
    prometheus_rule_files:
      this_is_rule_1_InstanceDown:
        src: ../../templates/rules/basic.rules
        dest: basic.rules
  roles:
    - { role: ansible-prometheus }
